- name: launch instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    port: 5986
    ami_id: ami-076c188b0006a9c1c
    instance_os: windows
  roles:
    - aws_multi_instances
