- name: launch instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    port: 5986
    ami_id: ami-0a174bb076b94a327
    instance_os: windows
  roles:
    - aws_multi_instances
