---

- name: add nodes
  bigip_node:
    server: "{{ hostvars[item]['inventory_hostname'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    host: "{{ inventory_hostname }}"
    name: "{{ inventory_hostname }}"
    validate_certs: "no"
  with_items: "{{ groups.tag_Name_ansible_bigip | first }}"

- name: create pool
  bigip_pool:
    server: "{{ hostvars[item]['inventory_hostname'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    name: "ansible_http_pool"
    lb_method: "round-robin"
    monitors: "/Common/http"
    monitor_type: "and_list"
    validate_certs: "no"
  with_items: "{{ groups.tag_Name_ansible_bigip | first }}"

- name: add nodes to pool
  bigip_pool_member:
    server: "{{ hostvars[item]['inventory_hostname'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    state: "present"
    name: "{{ inventory_hostname }}"
    host: "{{ inventory_hostname }}"
    port: "80"
    pool: "ansible_http_pool"
    validate_certs: "no"
  with_items: "{{ groups.tag_Name_ansible_bigip | first }}"

- name: add virtual server
  bigip_virtual_server:
    server: "{{ hostvars[item]['inventory_hostname'] }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    server_port: "8443"
    name: "ansible_virtual_server"
    destination: "{{ hostvars[item]['inventory_hostname'] }}"
    port: "443"
    enabled_vlans: "all"
    all_profiles: ['http','clientssl','oneconnect']
    pool: "ansible_http_pool"
    snat: "Automap"
    validate_certs: "no"
  with_items: "{{ groups.tag_Name_ansible_bigip | first }}"
