---

- name: close servicenow request
  snow_record:
    username: "{{ snow_user }}"
    password: "{{ snow_password }}"
    instance: "{{ snow_instance }}"
    state: present
    table: sc_request
    number: "{{ snow_request }}"
    data:
      work_notes: "Built host with IP - {{ item.public_ip }}"
      state: 3
  delegate_to: localhost
  become: false
  loop: "{{ ec2.instances }}"
  loop_control:
    label: "{{ item.public_ip }}"


- name: close servicenow request item
  snow_record:
    username: "{{ snow_user }}"
    password: "{{ snow_password }}"
    instance: "{{ snow_instance }}"
    state: present
    table: sc_req_item
    number: "RITM{{ snow_request.split('REQ')[1] }}"
    data:
      work_notes: "Built host with IP - {{ item.public_ip }}"
      state: 3
  delegate_to: localhost
  become: false

