---

- name: launch multiple instances
  ec2:
    region: "{{ ec2_region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_size }}"
    image: "{{ ami_id }}"
    wait: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    group: "{{ security_group }}"
    assign_public_ip: yes
    user_data: "{{ lookup('file', 'userdata.txt') | default(omit) }}" 
    instance_tags:
       role: webserver
       os: "{{ instance_os | default(linux) }}"
    count_tag:
      role: webserver
    exact_count: "{{ instance_count }}"
  register: ec2

- name: wait for connection
  wait_for:
    host: "{{ item.public_ip }}"
    port: "{{ port | default(22) }}"
    delay: 10
  loop: "{{ ec2.instances }}"
  loop_control:
    label: "{{ item.public_ip }}"



