---

- name: launch multiple instances
  ec2:
    region: "{{ ec2_region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_size }}"
    image: "{{ ami_id }}"
    wait: yes
    count: "{{ instance_count }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    group: "{{ security_group }}"
    assign_public_ip: yes
    instance_tags:
       role: webserver
  register: ec2

- name: wait for ssh to come up
  delegate_to: "{{ item.public_ip_address }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"


