---

- name: launch multiple instances
  ec2:
    region: "{{ ec2_region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_size }}"
    image: "{{ ami_id }}"
    wait: yes
    count: "{{ instance_count }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    group: "{{ security_group }}"
    assign_public_ip: yes
    instance_tags:
       role: webserver
    count_tag:
      role: webserver
    exact_count: "{{ instance_count }}"

  register: ec2

- name: wait for ssh
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 10
  loop: "{{ ec2.instances }}"
  loop_control:
    label: "{{ item.public_ip }}"



