---

- name: launch multiple instances
  ec2:
    region: "{{ ec2_region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_size }}"
    image: "{{ ami_id }}"
    wait: yes
    count: "{{ instance_count }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    group: "{{ security_group }}"
    assign_public_ip: yes
    user_data: "{{ lookup('file', '{{ os }}-userdata') }}"
  register: ec2_instance
