---

- name: launch f5 instance
  ec2:
    key_name: "{{ keypair }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_type: "{{ instance_size }}"
    group: "{{ security_group }}"
    assign_public_ip: yes
    image: "{{ ami_id }}"
    region: "{{ ec2_region }}"
    count: "{{ instance_count }}"
    wait: yes
  register: ec2_instance


- name: Wait for port to come up
  wait_for:
    port: "{{ port }}"
    delay: 10
    sleep: 10
    host: "{{ item.public_dns_name }}"
  with_items: "{{ ec2_instance.instances }}"
