---

- name: launch f5 instances
  ec2_instance:
    name: "ansible-{{ os }}"
    key_name: "{{ keypair }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_type: "{{ instance_size }}"
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami_id }}"
    user_data: "{{ lookup('file', '{{ os }}-userdata') }}"
    region: "{{ ec2_region }}"
  register: ec2_instance



- name: Wait for port to come up
  wait_for:
    port: "{{ port }}"
    delay: 10
    sleep: 10
    host: "{{ item.public_dns_name }}"
  with_items: "{{ ec2_instance.instances }}"
