---

- name: add local user
  win_user:
    name: pharriso
    password: Redhat123
    state: present

- name: manage local admins
  win_dsc:
    resource_name: Group
    GroupName: Administrators
    Ensure: Present
    MembersToInclude: pharriso

