---

- name: launch ec2 instances
  ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ keypair }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_type: "{{ instance_size }}"
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami_id }}"
    user_data: "{{ lookup('file', '{{ os }}-userdata') }}"
    region: "{{ ec2_region }}"
  register: ec2

- name: wait for ssh
  wait_for:
    host: "{{ ec2.instances[0].public_ip_address }}"
    port: 22
    delay: 10
